STABILITY TESTING: RAISER ENGINE

ERRORS

AttributeError (FIXED)
=========
This only happens on a reload when the current_session object is not initialised. Not a production concern. Solved by going to main menu, then reloading.

While running game code:
  File "game/script.rpy", line 838, in script
  File "game/script.rpy", line 838, in python
  File "game/script.rpy", line 367, in python
AttributeError: 'NoneType' object has no attribute 'map'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\Tekken6\Documents\Neerans Work\Other\renpy-6.15.7-sdk\renpy\execution.py", line 288, in run
    node.execute()
  File "C:\Users\Tekken6\Documents\Neerans Work\Other\renpy-6.15.7-sdk\renpy\ast.py", line 718, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Tekken6\Documents\Neerans Work\Other\renpy-6.15.7-sdk\renpy\python.py", line 1297, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 838, in <module>
    $ show_village_map(current_session.village, current_session.main_player)
  File "game/script.rpy", line 367, in show_village_map
    renpy.hide(village.map) # remove it first otherwise it does not show the new image on top
AttributeError: 'NoneType' object has no attribute 'map'

AttributeError (FIXED)
===============
Changing player.limbs to player.get_limbs()

While running game code:
  File "game/script.rpy", line 861, in script call
  File "game/script.rpy", line 861, in script call
  File "game/script.rpy", line 861, in script call
  File "game/script.rpy", line 861, in script call
  File "game/script.rpy", line 861, in script call
  File "game/script.rpy", line 861, in script call
  File "game/script.rpy", line 861, in script call
  File "game/script.rpy", line 872, in script
  File "game/script.rpy", line 872, in python
  File "game/missions.rpy", line 50, in python
  File "game/player.rpy", line 339, in python
AttributeError: Player instance has no attribute 'limbs'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\Tekken6\Documents\Neerans Work\Other\renpy-6.15.7-sdk\renpy\execution.py", line 288, in run
    node.execute()
  File "C:\Users\Tekken6\Documents\Neerans Work\Other\renpy-6.15.7-sdk\renpy\ast.py", line 718, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Tekken6\Documents\Neerans Work\Other\renpy-6.15.7-sdk\renpy\python.py", line 1297, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 872, in <module>
    $ current_session.mission.do_mission(current_session.main_player, current_session.village, random.choice(ALL_VILLAGES))
  File "game/missions.rpy", line 50, in do_mission
    player.injury_chance(0.05)
  File "game/player.rpy", line 339, in injury_chance
    random.choice(self.limbs).injure()
AttributeError: Player instance has no attribute 'limbs'