I'm sorry, but an uncaught exception occurred.

While executing init code:
  File "game/script.rpy", line 38, in script
  File "game/script.rpy", line 278, in python
NameError: name 'ShopItem' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\Tekken6\Documents\Neerans Work\Other\renpy-6.15.7-sdk\renpy\execution.py", line 288, in run
    node.execute()
  File "C:\Users\Tekken6\Documents\Neerans Work\Other\renpy-6.15.7-sdk\renpy\ast.py", line 718, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Tekken6\Documents\Neerans Work\Other\renpy-6.15.7-sdk\renpy\python.py", line 1297, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 278, in <module>
    i_heal_paste = ShopItem("Heal Paste", 300, 30, health=30)
NameError: name 'ShopItem' is not defined

Windows-7-6.1.7601-SP1
Ren'Py 6.15.7.374
A Ren'Py Game 0.0
